Update from 5 Dec 2022
GSA/govt-urls pull request #79
Opened 2022-12-05 21:40 UTC by h-m-f-t

Resolves #26, closes #37, fixes #39, resolves #55

2023-01-30 20:53 UTC, dawnpm commented on 1_govt_urls_full.csv
> +shopvcs.com,Department of Veterans Affairs,,Website,Federal,Executive,,Redirecrts to https://shopvcs.va.gov/,,
typo here

2023-01-30 20:55 UTC, dawnpm commented on 1_govt_urls_full.csv
> +okdhslive.org,,OK Human Services Department,,State,Executive,Oklahoma,,,
Does branch apply at the State level?

2023-01-30 20:55 UTC, dawnpm requested changes
a typo and a question, thanks.

2023-02-15 19:49 UTC, h-m-f-t commented
Bumping this again 👋

2023-02-22 21:09 UTC, dawnpm approved these changes

2023-02-22 21:43 UTC, merged